#include <bits/stdc++.h>
using namespace std;

const int N = 1e5 + 5;

vector<pair<int,int>> adj[N];
int n, m;
int dist[N];
bool vis[N];

void dijkstra_shortest(int start) {
    priority_queue<pair<int,int>, vector<pair<int,int>>, greater<pair<int,int>>> pq;
    memset(dist, 0x3f, sizeof(dist));
    memset(vis, false, sizeof(vis));
    dist[start] = 0;
    pq.push({0, start});
    while(!pq.empty()) {
        int u = pq.top().second;
        pq.pop();
        if(vis[u]) continue;
        vis[u] = true;
        for(auto e : adj[u]) {
            int v = e.first, w = e.second;
            if(dist[v] > dist[u] + w) {
                dist[v] = dist[u] + w;
                pq.push({dist[v], v});
            }
        }
    }
}

void dijkstra_longest(int start) {
    priority_queue<pair<int,int>> pq;
    memset(dist, -0x3f, sizeof(dist));
    memset(vis, false, sizeof(vis));
    dist[start] = 0;
    pq.push({0, start});
    while(!pq.empty()) {
        int u = pq.top().second;
        pq.pop();
        if(vis[u]) continue;
        vis[u] = true;
        for(auto e : adj[u]) {
            int v = e.first, w = e.second;
            if(dist[v] < dist[u] + w) {
                dist[v] = dist[u] + w;
                pq.push({dist[v], v});
            }
        }
    }
}

int main() {
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w", stdout);

    cin >> n >> m;
    for(int i = 0; i < m; i++) {
        int u, v, w;
        cin >> u >> v >> w;
        adj[u].push_back({v, w});
    }

    dijkstra_shortest(0);
    int expected_shortest_path = dist[n-1];

    dijkstra_longest(0);
    int expected_longest_path = dist[n-1];

    // Read the output file generated by the solution program
    int shortest_path, longest_path;
    cin >> shortest_path >> longest_path;

    // Compare the expected and actual output
    if (shortest_path == expected_shortest_path && longest_path == expected_longest_path) {
        cout << "Correct" << endl;
    } else {
        cout << "Incorrect" << endl;
    }

    return 0;
}
